### PR TITLE
Fix typecheck bug with casts

### LINKED ISSUE #116: Constant folding gives wrong answer for ToAddress
In the compiler, constant folding of a expression like `address(someUint)` should truncate the value of `someUint` to 160 bits.  Currently it doesn't do any masking.

An example expression that yields the wrong result is `address(hash(0))`

### PR DESCRIPTION
**Pull request by RGates94**
Fixes a bug where casts like `uint`, `int`, `bytes32`, and `address` casts did not check if the subexpression is of the correct type if it was a constant. For example, previously, the statement `let x = address(None<uint>);` would compile.

This also fixes #116.

### CODE REVIEW

File: src/compile/typecheck.rs [hunk 1]
```diff
@@ -2187,8 +2187,19 @@ fn typecheck_unary_op(
...
         UnaryOp::ToAddress => {
-            if let TypeCheckedExprKind::Const(val, _) = sub_expr.kind {
-                Ok(TypeCheckedExprKind::Const(val, Type::EthAddress))
+            if let TypeCheckedExprKind::Const(Value::Int(val), _) = sub_expr.kind {
+                Ok(TypeCheckedExprKind::Const(
+                    Value::Int(
+                        val.modulo(
+                            &Uint256::from_string_hex(
+                                "1__0000_0000__0000_0000__0000_0000__0000_0000__0000_0000",
+                            ) //2^40, 1+max address
```
Comment (edfelten) [inline src/compile/typecheck.rs:2196]: Isn't this really 2^160?

**Review by edfelten — CHANGES_REQUESTED** [review]
Just one apparent error in a comment.  Otherwise good to go.

File: src/compile/typecheck.rs (hunk 1 above)
Comment (RGates94) [reply src/compile/typecheck.rs:2196]: Yes, I'll fix that.

**Review by edfelten — APPROVED** [review]
Looks good.
